services:
  postgres:
    image: postgres:16
    container_name: miauwuauf_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: miauwuauf
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: miauwuauf_backend
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "5555:5555"
    command: node src/server.js
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/miauwuauf?schema=public
    volumes:
      - ./backend:/app
    working_dir: /app

volumes:
  pgdata:
